# ovejas para desplegar un cluster de Hadoop
# Desplegar previamente MVs router, control y dhcpdns
#
# Usage:
#    ansible-playbook --ask-vault IpDM-ovejas-centos-8.yaml
#
---
- name: Clonando MVs. Ovejas para hadoop
  hosts: localhost
  gather_facts: false

# Variables
# --

# archivo encriptado con ansible-vault que contiene la variable
# {{ ovirt_password }} con la clave para acceder al IaaS ULL

  vars_files:
    - password.yml

# Clave SSH para el usuario ansible (usen la que generaron en 
# la MV control

  vars:
    ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDL7VuFFqr0t2m65Wyfiup0qFBBYcmbbdFPCCUNpzRnSbuZhtLuTGnRQDixoCGwURHsvs4nGyD0Lky1hgoa+iWu14J5dRTH2VdvZ9LXRnApuDe/F1ihCl4ijZVV8PBqcqcAtW/vcCe5VteyO2WaYr0/G6eydI7HuNYqACvBj+qlh/6lFboatiesCkqSIImJZcTCjKsU+OpLJ3d/GzXPOTRfnq83aOXeyrySy037PIwNyXyyLuQ7PO0JD38+3HlfzqILGqhPg8hLyu/jKVmcRtTSXYu/uFqMe9M0D9XlYLl/2KSABP7PgvLaCX6mcs/pbr2BjgxDkwLfNr/izGn7pxE8IFzPca6y5SYoBqqvGvtTauXAt9kyvGxmqPSgv6aEtBy1QKl8UaYaMMLZkzlyT35K0WXcmjWjavEzBAhZLlmLLurIPl7P/LB+xVCCoplXVZ9uGmi/0LyfjOLK+gC/Hzb3azw8s0c3K4NzA4PZrTMpf2BWtlXTtfCsgBc0yX0mAw0= usuario@ubuntu

# Usuario IaaS (cambiar vblanco por aluxxx...)

    ovirt_login: alu0101103181@ULL

# Nodos a crear (en este caso dos ovejas)

    prefix: AITS
    nodes:
      - name: Backend-1-deb-p
      - name: Backend-2-deb-p
                                                                                                               1,1           Top
