# ovejas para desplegar un cluster de Hadoop
# Desplegar previamente MVs router, control y dhcpdns
#
# Usage:
#    ansible-playbook --ask-vault IpDM-ovejas-centos-8.yaml
#
---
- name: Clonando MVs. Ovejas para hadoop
  hosts: localhost
  gather_facts: false

# Variables
# --

# archivo encriptado con ansible-vault que contiene la variable
# {{ ovirt_password }} con la clave para acceder al IaaS ULL

  vars_files:
    - passPablo.yaml

# Clave SSH para el usuario ansible (usen la que generaron en 
# la MV control

  vars:
    ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIgHSIGFl526XIjSdUNlUraCtJr7YIICj6kresmgH+15ThptIiXTBjS5d116vA/A6DSce2ZEv34FuYDdr4upTZEFQqELc5X2SDZ/YXN54jyUtEjde9uutMvRFsGpflwJT2OT5jlXUBEtdf2+PeIEr4Wa/abe/dSFsaQ+/daFL1fFvqoZfq4U84SVrMd9eEH+zQ4tR77U2iFWj+lGY55BCgXYPlXLOluUFxznRLfwjA5b+oqsJFUR0YnPdeHNghs4WHYk3rT+btDrsBcM5S63/XpMT6sHX4NgXbw1Fh2fKvvU0ApHDt+bWHq24bd7SYWSc5WnzPCy/Sxpdz4aD2M3MBM6Relz3I4+DLyNPE7Z/ckq69TC8iSXkRFkUpOGr4aFzwBeO1WvjRL924zS+7rPCLwcmcSb9H9XdMLCmyzFScAHTOJM9nE6SnX14LuOC7WDl80s6ybkMTsbEat/NdyRDby+x+uWnPsVugiLPsaBMi8Pvq1gB3Zrp6uVzkc3B1AaE= usuario@ubuntu

# Usuario IaaS (cambiar vblanco por aluxxx...)

    ovirt_login: alu0101103181@ULL

# Nodos a crear (en este caso dos ovejas)

    prefix: AITS
    nodes:
      - name: Nginx-deb-p


# Especifiquen aqui el perfil de la red privada
# que tienen asignada

    node_nics: 
      - name: nic1
        profile_name: DOC1
      - name: nic2
        profile_name: DOCP2P-4002

# Tareas
# ------

  tasks:
    - name: Login to IaaS
      ovirt_auth:
        url: https://iaas.ull.es/ovirt-engine/api
        insecure: yes
        username: "{{ ovirt_login }}"
        password: "{{ ovirt_password }}"
        headers:
          filter: true

    - name: Create a VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: Cluster-Rojo
        name: "{{ prefix }}-{{ item.name }}"
        cpu_cores: 1
        cpu_sockets: 1
        memory: 1GiB
        #template: centos-8-sinred-cloudinit
        template: debian-10-sinred-cloudinit
        nics: "{{ node_nics }}"
        state: present
        wait: yes
      with_items: "{{ nodes }}"
    
    - name: Update VM via cloud-init
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ prefix }}-{{ item.name }}"
        state: running
        cloud_init_nics:
          - nic_name: ens3
            nic_boot_protocol: dhcp
            nic_on_boot: yes
          - nic_name: ens4
            nic_boot_protocol: dhcp      
            nic_on_boot: True
        cloud_init:
          host_name: "{{ item.name }}"
          user_name: ansible

# Passwd generado con mkpasswd -m SHA-512 alumno2020
# La clave en claro es: alumno2020
          root_password: $6$PWHnpEFE9q$fz0Vms/xmppsxrxLfm9f0nko9NdKICsMzulhLDttiJE254a1/MnUXvJSpCV1NgdnWG4UV5i54jqURubvIPjHA/

          authorized_ssh_keys: "{{ ssh_keys }}"
          custom_script: |
            write_files:
              - path: /etc/sudoers.d/ansible
                permissions: '0644'
                content: |
                  ansible ALL=(ALL) NOPASSWD:ALL
              - path: /tmp/saludos.txt
                permissions: '0644'
                content: |
                  "Que pasa pisha"
            runcmd:
              - sed -i '/AllowUsers/c\AllowUsers adminstic usuario soporteiass ansible hadoop' /etc/ssh/sshd_config
              - systemctl restart sshd
        wait: yes
      with_items: "{{ nodes }}"

    - name: Cleanup IaaS auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
